### ISSUE TITLE
in_opus err -129 Offline

### ISSUE THREAD

**Issue by schivore** [RamonUnch/in_opus#4]
Hello

I can read mp3 files without a problem, but cannot read opus files located either in the winamp drive nor on my NAS drive.
The error I get is in_opus err -129 Offline

I will try to fiddle with the plugin a but more, but any help would be appreciated.

Thanks for developing this plugin.

![Screen Shot 2022-12-06 at 09 53 26](https://user-images.githubusercontent.com/19815775/205878427-a4e22b12-45f4-4389-9194-7d8ae1c7ebfb.png)

**Comment by schivore** [comment]
thank you that makes sense, removing the kanjis worked! 

I thought I was using winamp 5.05 (see screenshot) but since I am playing it via PlayOnMac on Mac Os X and the opus files are on a mounted folder pointing to a NAS drive, the problem is probably on my side somewhere along the chain :)

Thanks for this excellent plugin 👍 

![Screen Shot 2022-12-06 at 12 59 18](https://user-images.githubusercontent.com/19815775/205919303-51e81366-5d9c-4cc7-8305-c7dcbed3bea9.png)

**Comment by RamonUnch** [comment]
Actually I think Winamp supports Unicode only since version 5.3
I was able to make a somewhat reliable routine to resolve file names.
Have a try with this build:

[in_opus_v0.913test.zip](https://github.com/RamonUnch/in_opus/files/10166970/in_opus_v0.913test.zip)

It should work as long as turning special characters to ? will not create file name collision and as long as the directory contains only ANSI characters.

So the idea is:

```
x:\Path\Without\non\ANSI\characters
* file1日.opus
* file2本.opus
* file1語.opus
```
In this case you will be able to play files `file2本.opus` but not `file1日.opus` or `file1語.opus` because I cannot know from `file1?.opus` which one it is.

**Comment by RamonUnch** [comment]
This is strange however, I did not write any MacOS support, So I do not know how you can run a Win32 plugin on MasOS?

**Comment by schivore** [comment]
PlayOnMac creates a virtual C drive on the Mac hard drive, namely in: 
/Users/mac/Library/PlayOnMac/wineprefix/Winamp/drive_c/Program Files/Winamp/Plugins
I saved your plugin in there and it worked right away.

**Comment by schivore** [comment]
Thanks for the routine, it works very well (despite the "in_opus err - 129 Offline" warning appearing in the Playlist window, the file plays perfectly well). It saves me the hassle of renaming my collection of opus files.

Thanks again.


![Screen Shot 2022-12-06 at 15 13 55](https://user-images.githubusercontent.com/19815775/205950199-99ef4b1a-11ea-4b7d-94f2-3a21d37a2b73.png)
